FROM php:8.2-apache

RUN chown -R www-data:www-data /var/www/html \
    && find /var/www/html -type d -exec chmod 755 {} \; \
    && find /var/www/html -type f -exec chmod 644 {} \;

RUN apt-get update && apt-get install -y \
  build-essential \
  libpng-dev \
  libjpeg-dev \
  libfreetype-dev \
  libonig-dev \
  libxml2-dev \
  libzip-dev \
  libssl-dev \
  zip \
  unzip \
  git \
  curl \
  mariadb-client \
  libicu-dev \
  && docker-php-ext-configure gd --with-freetype --with-jpeg \
  && docker-php-ext-install -j$(nproc) \
  pdo \
  pdo_mysql \
  mbstring \
  exif \
  pcntl \
  bcmath \
  gd \
  xml \
  zip \
  intl

COPY --from=composer/composer:2-bin /composer /usr/bin/composer

WORKDIR /var/www/html

COPY . .

RUN a2enmod rewrite

RUN composer install --no-dev --no-interaction --optimize-autoloader \
  && chown -R www-data:www-data /var/www/html

HEALTHCHECK --interval=1m --timeout=10s \
  CMD curl -f http://localhost/ || exit 1


EXPOSE 80